Question-1

In [1]:
import numpy as np

A = np.array([[2,6,9],
              [7,3,9],
              [4,8,2]])

B = np.array([[11,54,36],
             [21,85,37],
             [45,14,23]])

C = np.array([[0,0,0],
             [0,0,0],
             [0,0,0]])

for i in range(len(A)):
    for j in range(len(A[i])):
        C[i][j] = A[i][j] + B[i][j]

for k in C:
    print(k)
    

[13 60 45]
[28 88 46]
[49 22 25]


Question-2

In [9]:
X = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
    
Y = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
Z = [[0, 0, 0, 0],
     [0, 0, 0, 0],
    [0, 0, 0, 0]]

for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            Z[i][j] += X[i][k] * Y[k][j]
            
for l in Z:
    print(l)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


Question-3

In [12]:
M = np.array([[55,3,9,7],
              [25,36,98,71],
              [1,3,6,7],
              [35,54,66,44]])

N = np.array([[0,0,0,0],
              [0,0,0,0],
              [0,0,0,0],
              [0,0,0,0]])

for i in range(len(M)):
    for j in range(len(M[0])):
        N[i][j] = M[j][i]

for k in N:
    print(k)

[55 25  1 35]
[ 3 36  3 54]
[ 9 98  6 66]
[ 7 71  7 44]


Question-4

In [15]:
a = ['Flash', 'Batman', 'Joker', 'Necron', 'Lobo']

a.sort()

print(a)

['Batman', 'Flash', 'Joker', 'Lobo', 'Necron']


Question-5

In [20]:
import re

b = 'sdfrewfr  ,  ewjhffjn  .  ioyu65oiu  ;  qoweiu'

c = re.sub('[^\w\s]', '', b)    # [^\w\s] : any character which is not a word, number or space

print(c)

sdfrewfr    ewjhffjn    ioyu65oiu    qoweiu
